services:
  stub_server:
    build: ../stub_server
    image: hlc21_stub_server
    ports:
      - "8000:8000"
    environment:
      DEFAULT_RATE_LIMIT: 1000 per second

  client:
    build: .
    image: ${HLC21_CLIENT_IMAGE}
    environment:
      ADDRESS: stub_server
    depends_on:
      stub_server:
        condition: service_healthy
